source 'https://github.com/CocoaPods/Specs.git'
source "ssh://internal.smartdevices.com.cn:29418/apps/Specs-iOS"

platform :ios, '8.0'

target 'DiscoveryDemo' do
  # use_frameworks!
    pod 'HMAccountSDK', '2.3.1'
    pod 'DDSocial/MI','1.6.1'
    pod 'DDSocial/Share','1.6.1'
    pod 'MiFitReact', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    ]
end
